# Ruby

## Общие советы

* Старайтесь использовать последнюю стабильную версию Ruby

  Следите за обновлениями и развитием языка на [официальном сайте](https://www.ruby-lang.org/), изучайте последние
  изменения и старайтесь разумно использовать его новые возможности.

* Используйте `Hash#fetch` вместо `Hash#[]` для проверки наличия ключей

  Лучший способ убедиться, существует ли ключ в хэше и получить этот ключ, это использовать метод
  [fetch](http://www.ruby-doc.org/core-2.1.3/Hash.html#method-i-fetch). При отсутствии ключа в хэше `fetch` вызовет
  исключение `KeyError`, которое намного удобнее обработать, чем где-то ещё `NoMethodError` для nil.

## Синтаксис

* Используйте новый лаконичный синтаксис хэшей

  Вместо `{ :key => 'value', :key2 => 'value2' }` используйте `{ key: 'value', key2: 'value2' }`

## Обработка исключений

* Обрабатывайте только нужные исключения

  Из-за особенностей [иерархии классов](http://blog.nicksieger.com/articles/2006/09/06/rubys-exception-hierarchy/)
  исключений, никогда не перехватывайте класс `Exception`, это грозит непредсказуемым поведением работы программы.
  Перехватывайте только те классы исключений, которые ожидаете обработать, либо те, которые можете с уверенностью
  проигнорировать. Использование begin/rescue/end конструкции без явного указания типа исключений - плохой тон и
  возможность пропустить критические ошибки, которые никогда не попадут в лог.

* Создавайте свои классы исключений

  Использование в своём коде собственные классы исключений поможет получить более детальную информацию о причине
  возникновения ошибки и правильно её обработать. Наследуйте собственные классы исключений от класса не выше чем
  `StandardError`.

* Лаконично обрабатывайте исключения внутри коротких методов

  В некоторых случаях, когда вы хотите обработать исключение внутри нестабильного метода, будет более логично перенести
  `rescue` в самый конец метода, опустив избыточные `begin` и `end`. Это отделит смысловую часть и обработку исключения.

  ```ruby
  def some_unstable_method
    # основной код
  rescue SomeException
    # обрабатываем исключения
  end
  ```
